In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("C:/Users/harin/Downloads/Personal Loan/loan_Modelling.csv")
print(df.head(5))

   ID  Age  Experience  Income  ZIPCode  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49    91107       4    1.6          1         0
1   2   45          19      34    90089       3    1.5          1         0
2   3   39          15      11    94720       1    1.0          1         0
3   4   35           9     100    94112       1    2.7          2         0
4   5   35           8      45    91330       4    1.0          2         0

   Personal_Loan  Securities_Account  CD_Account  Online  CreditCard
0              0                   1           0       0           0
1              0                   1           0       0           0
2              0                   0           0       0           0
3              0                   0           0       0           0
4              0                   0           0       0           1

In [8]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIPCode             5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal_Loan       5000 non-null   int64
 10  Securities_Account  5000 non-null   int64
 11  CD_Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB
None

In [9]:
print(df.describe())

                ID          Age   Experience       Income       ZIPCode  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000
mean   2500.500000    45.338400    20.104600    73.774200  93169.257000
std    1443.520003    11.463166    11.467954    46.033729   1759.455086
min       1.000000    23.000000    -3.000000     8.000000  90005.000000
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000
max    5000.000000    67.000000    43.000000   224.000000  96651.000000

            Family        CCAvg    Education     Mortgage  Personal_Loan  \
count  5000.000000  5000.000000  5000.000000  5000.000000    5000.000000
mean      2.396400     1.937938     1.881000    56.498800       0.096000
std       1.147663     1.747659     0.839869   101.713802       0.294621
min       1.000000     0.000000     1.000000     0.000000       0.000000
25%       1.000000     0.700000     1.000000     0.000000       0.000000
50%       2.000000     1.500000     2.000000     0.000000       0.000000
75%       3.000000     2.500000     3.000000   101.000000       0.000000
max       4.000000    10.000000     3.000000   635.000000       1.000000

       Securities_Account  CD_Account       Online   CreditCard
count         5000.000000  5000.00000  5000.000000  5000.000000
mean             0.104400     0.06040     0.596800     0.294000
std              0.305809     0.23825     0.490589     0.455637
min              0.000000     0.00000     0.000000     0.000000
25%              0.000000     0.00000     0.000000     0.000000
50%              0.000000     0.00000     1.000000     0.000000
75%              0.000000     0.00000     1.000000     1.000000
max              1.000000     1.00000     1.000000     1.000000

In [10]:
print(df['ZIPCode'].nunique())

467

In [11]:
df['ZIPCode'] = df['ZIPCode'].astype('category')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIPCode             5000 non-null   category
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal_Loan       5000 non-null   int64
 10  Securities_Account  5000 non-null   int64
 11  CD_Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: category(1), float64(1), int64(12)
memory usage: 521.4 KB
None

In [12]:
df.drop(['ZIPCode'], axis=1, inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   Family              5000 non-null   int64
 5   CCAvg               5000 non-null   float64
 6   Education           5000 non-null   int64
 7   Mortgage            5000 non-null   int64
 8   Personal_Loan       5000 non-null   int64
 9   Securities_Account  5000 non-null   int64
 10  CD_Account          5000 non-null   int64
 11  Online              5000 non-null   int64
 12  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(12)
memory usage: 507.9 KB

In [14]:
df[['Experience', 'Age']].head(10)

   Experience  Age
0           1   25
1          19   45
2          15   39
3           9   35
4           8   35
5          13   37
6          27   53
7          24   50
8          10   35
9           9   34

In [15]:
df[df['Experience'] < 0]

,ID,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
89,90,25,-1,113,4,2.30,3,0,0,0,0,0,1
226,227,24,-1,39,2,1.70,2,0,0,0,0,0,0
315,316,24,-2,51,3,0.30,3,0,0,0,0,1,0
451,452,28,-2,48,2,1.75,3,89,0,0,0,1,0
524,525,24,-1,75,4,0.20,1,0,0,0,0,1,0
536,537,25,-1,43,3,2.40,2,176,0,0,0,1,0
540,541,25,-1,109,4,2.30,3,314,0,0,0,1,0
576,577,25,-1,48,3,0.30,3,0,0,0,0,0,1
583,584,24,-1,38,2,1.70,2,0,0,0,0,1,0
597,598,24,-2,125,2,7.20,1,0,0,1,0,0,1
649,650,25,-1,82,4,2.10,3,0,0,0,0,1,0
670,671,23,-1,61,4,2.60,1,239,0,0,0,1,0
686,687,24,-1,38,4,0.60,2,0,0,0,0,1,0
793,794,24,-2,150,2,2.00,1,0,0,0,0,1,0
889,890,24,-2,82,2,1.60,3,0,0,0,0,1,1
909,910,23,-1,149,1,6.33,1,305,0,0,0,0,1
1173,1174,24,-1,35,2,1.70,2,0,0,0,0,0,0
1428,1429,25,-1,21,4,0.40,1,90,0,0,0,1,0
1522,1523,25,-1,101,4,2.30,3,256,0,0,0,0,1
1905,1906,25,-1,112,2,2.00,1,241,0,0,0,1,0
2102,2103,25,-1,81,2,1.60,3,0,0,0,0,1,1
2430,2431,23,-1,73,4,2.60,1,0,0,0,0,1,0
2466,2467,24,-2,80,2,1.60,3,0,0,0,0,1,0
2545,2546,25,-1,39,3,2.40,2,0,0,0,0,1,0
2618,2619,23,-3,55,3,2.40,2,145,0,0,0,1,0
2717,2718,23,-2,45,4,0.60,2,0,0,0,0,1,1
2848,2849,24,-1,78,2,1.80,2,0,0,0,0,0,0
2876,2877,24,-2,80,2,1.60,3,238,0,0,0,0,0
2962,2963,23,-2,81,2,1.80,2,0,0,0,0,0,0
2980,2981,25,-1,53,3,2.40,2,0,0,0,0,0,0
3076,3077,29,-1,62,2,1.75,3,0,0,0,0,0,1
3130,3131,23,-2,82,2,1.80,2,0,0,1,0,0,1
3157,3158,23,-1,13,4,1.00,1,84,0,0,0,1,0
3279,3280,26,-1,44,1,2.00,2,0,0,0,0,0,0
3284,3285,25,-1,101,4,2.10,3,0,0,0,0,0,1
3292,3293,25,-1,13,4,0.40,1,0,0,1,0,0,0
3394,3395,25,-1,113,4,2.10,3,0,0,0,0,1,0
3425,3426,23,-1,12,4,1.00,1,90,0,0,0,1,0
3626,3627,24,-3,28,4,1.00,3,0,0,0,0,0,0
3796,3797,24,-2,50,3,2.40,2,0,0,1,0,0,0
3824,3825,23,-1,12,4,1.00,1,0,0,1,0,0,1
3887,3888,24,-2,118,2,7.20,1,0,0,1,0,1,0
3946,3947,25,-1,40,3,2.40,2,0,0,0,0,1,0
4015,4016,25,-1,139,2,2.00,1,0,0,0,0,0,1
4088,4089,29,-1,71,2,1.75,3,0,0,0,0,0,0
4116,4117,24,-2,135,2,7.20,1,0,0,0,0,1,0
4285,4286,23,-3,149,2,7.20,1,0,0,0,0,1,0
4411,4412,23,-2,75,2,1.80,2,0,0,0,0,1,1
4481,4482,25,-2,35,4,1.00,3,0,0,0,0,1,0
4514,4515,24,-3,41,4,1.00,3,0,0,0,0,1,0
4582,4583,25,-1,69,3,0.30,3,0,0,0,0,1,0
4957,4958,29,-1,50,2,1.75,3,0,0,0,0,0,1

In [16]:
df[df['Experience'] < 0]['Personal_Loan'].value_counts()
df[df['Experience'] < 0]['Personal_Loan'].mean()

np.float64(0.0)

In [17]:
df['Experience'] = df['Experience'].abs()

In [18]:
df['Experience'].min()

np.int64(0)

In [19]:
df['calculated_start_age'] = df['Age'] - df['Experience']
df['calculated_start_age'].describe()

count    5000.000000
mean       25.203800
std         1.254982
min        20.000000
25%        24.000000
50%        25.000000
75%        26.000000
max        30.000000
Name: calculated_start_age, dtype: float64

In [20]:
df[['Age', 'Experience']].corr()

                 Age  Experience
Age         1.000000    0.993991
Experience  0.993991    1.000000

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    5000 non-null   int64
 1   Age                   5000 non-null   int64
 2   Experience            5000 non-null   int64
 3   Income                5000 non-null   int64
 4   Family                5000 non-null   int64
 5   CCAvg                 5000 non-null   float64
 6   Education             5000 non-null   int64
 7   Mortgage              5000 non-null   int64
 8   Personal_Loan         5000 non-null   int64
 9   Securities_Account    5000 non-null   int64
 10  CD_Account            5000 non-null   int64
 11  Online                5000 non-null   int64
 12  CreditCard            5000 non-null   int64
 13  calculated_start_age  5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [22]:
df['ID'] = df['ID'].astype('category')

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    5000 non-null   category
 1   Age                   5000 non-null   int64
 2   Experience            5000 non-null   int64
 3   Income                5000 non-null   int64
 4   Family                5000 non-null   int64
 5   CCAvg                 5000 non-null   float64
 6   Education             5000 non-null   int64
 7   Mortgage              5000 non-null   int64
 8   Personal_Loan         5000 non-null   int64
 9   Securities_Account    5000 non-null   int64
 10  CD_Account            5000 non-null   int64
 11  Online                5000 non-null   int64
 12  CreditCard            5000 non-null   int64
 13  calculated_start_age  5000 non-null   int64
dtypes: category(1), float64(1), int64(12)
memory usage: 556.8 KB

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

ID                      0
Age                     0
Experience              0
Income                  0
Family                  0
CCAvg                   0
Education               0
Mortgage                0
Personal_Loan           0
Securities_Account      0
CD_Account              0
Online                  0
CreditCard              0
calculated_start_age    0
dtype: int64

In [26]:
df.drop(['ID','calculated_start_age'], axis=1, inplace=True)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 5000 non-null   int64
 1   Experience          5000 non-null   int64
 2   Income              5000 non-null   int64
 3   Family              5000 non-null   int64
 4   CCAvg               5000 non-null   float64
 5   Education           5000 non-null   int64
 6   Mortgage            5000 non-null   int64
 7   Personal_Loan       5000 non-null   int64
 8   Securities_Account  5000 non-null   int64
 9   CD_Account          5000 non-null   int64
 10  Online              5000 non-null   int64
 11  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(11)
memory usage: 468.9 KB

In [28]:
df.describe()

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,45.338400,20.134600,73.774200,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,11.463166,11.415189,46.033729,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,23.000000,0.000000,8.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,35.000000,10.000000,39.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,45.000000,20.000000,64.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,55.000000,30.000000,98.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,67.000000,43.000000,224.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [29]:
df['Personal_Loan'].value_counts()

Personal_Loan
0    4520
1     480
Name: count, dtype: int64

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('Personal_Loan', axis=1),
    df['Personal_Loan'],
    test_size=0.2,
    random_state=42,
    stratify=df['Personal_Loan']
)

In [33]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

Personal_Loan
0    0.904
1    0.096
Name: proportion, dtype: float64

In [34]:
m1 = DecisionTreeClassifier(
    class_weight='balanced',
    random_state=42
)

In [35]:
m1.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [36]:
y_pred = m1.predict(X_test)

In [37]:
from sklearn.metrics import classification_report, confusion_matrix

In [38]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       904
           1       0.89      0.97      0.93        96

    accuracy                           0.98      1000
   macro avg       0.94      0.98      0.96      1000
weighted avg       0.99      0.98      0.99      1000

In [39]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[892  12]
 [  3  93]]

In [42]:
!pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\harin\downloads\finflow\venv\lib\site-packages (from imbalanced-learn) (2.4.6)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\harin\downloads\finflow\venv\lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\harin\downloads\finflow\venv\lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\harin\downloads\finflow\venv\lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\harin\downloads\finflow\venv\lib\site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.2-py3-none-any.whl (236 kB)
Downloading sklearn_compat-0.1.6-py3-none-any.whl (22 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.2 sklearn-compat-0.1.6

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
from imblearn.over_sampling import SMOTE

In [44]:
smote = SMOTE(random_state=42)

In [45]:
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [46]:
m2 = DecisionTreeClassifier(random_state=42)

In [47]:
m2.fit(X_train_smote, y_train_smote)

DecisionTreeClassifier(random_state=42)

In [48]:
y_pred_m2 = m2.predict(X_test)

In [49]:
print("Classification Report:")
print(classification_report(y_test, y_pred_m2))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       904
           1       0.77      0.96      0.85        96

    accuracy                           0.97      1000
   macro avg       0.88      0.96      0.92      1000
weighted avg       0.97      0.97      0.97      1000

In [50]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_m2))

Confusion Matrix:
[[876  28]
 [  4  92]]

In [51]:
print("Model 1 train accuracy:", m1.score(X_train, y_train))
print("Model 1 test accuracy:", m1.score(X_test, y_test))

Model 1 train accuracy: 1.0
Model 1 test accuracy: 0.985

In [52]:

print("Model 2 train accuracy:", m2.score(X_train_smote, y_train_smote))
print("Model 2 test accuracy:", m2.score(X_test, y_test))

Model 2 train accuracy: 1.0
Model 2 test accuracy: 0.968

In [53]:
m1.get_depth()

17

In [54]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [5, 8, 11, 14, 17, None],
    'min_samples_leaf': [20, 40, 60, 80, 100],
    'min_samples_split': [40, 80, 120, 160, 200]
}

In [55]:
# Model 1: class_weight version — search on original data
grid_search_1 = GridSearchCV(
    estimator=DecisionTreeClassifier(class_weight='balanced', random_state=42),
    param_grid=param_grid,
    scoring='f1',
    cv=5,
    n_jobs=-1
)
grid_search_1.fit(X_train, y_train)

print("Best params (Model 1):", grid_search_1.best_params_)
print("Best CV F1 score (Model 1):", grid_search_1.best_score_)

best_m1 = grid_search_1.best_estimator_
y_pred_best_m1 = best_m1.predict(X_test)

print("\nModel 1 (tuned) Classification Report:")
print(classification_report(y_test, y_pred_best_m1))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_m1))

Best params (Model 1): {'max_depth': 8, 'min_samples_leaf': 20, 'min_samples_split': 40}
Best CV F1 score (Model 1): 0.812092332234473

Model 1 (tuned) Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       904
           1       0.66      0.99      0.79        96

    accuracy                           0.95      1000
   macro avg       0.83      0.97      0.88      1000
weighted avg       0.97      0.95      0.95      1000

Confusion Matrix:
[[855  49]
 [  1  95]]

In [57]:
# Model 2: SMOTE version — search on SMOTE-balanced data
grid_search_2 = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid=param_grid,
    scoring='f1',
    cv=5,
    n_jobs=-1
)
grid_search_2.fit(X_train_smote, y_train_smote)

print("\nBest params (Model 2):", grid_search_2.best_params_)
print("Best CV F1 score (Model 2):", grid_search_2.best_score_)

best_m2 = grid_search_2.best_estimator_
y_pred_best_m2 = best_m2.predict(X_test)

print("\nModel 2 (tuned) Classification Report:")
print(classification_report(y_test, y_pred_best_m2))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_m2))

Best params (Model 2): {'max_depth': 11, 'min_samples_leaf': 20, 'min_samples_split': 40}
Best CV F1 score (Model 2): 0.9520936757762065

Model 2 (tuned) Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       904
           1       0.73      0.97      0.83        96

    accuracy                           0.96      1000
   macro avg       0.86      0.97      0.91      1000
weighted avg       0.97      0.96      0.97      1000

Confusion Matrix:
[[870  34]
 [  3  93]]